# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2dc5dd551d6397a9c18977f83840764c0c380ddc90eb1e8e639cc09c84b30db9132ae20603b48552608c569ebd7e3072ebee861c603c4e8f9a5d32f5fe4d2bb4

test:
  secret_key_base: 47277e4ecf8c437e972aefa83e754c4cf9d18f6abb1caacc78eb77bf789926445b794907c01da8055e6195d8ae4e162d324cf929688af291c86e114101f64cb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
